import type { Metadata } from "next";
// import localFont from "next/font/local";
import "../../styles/globals.css";
import { cn } from "@/lib/utils";
import HeaderNav from "@/components/HeaderNav/HeaderNav";
import WagmiConfigProvider from "@/contexts/WagmiProvider";
import { Toaster } from "@/components/ui/toaster";
import { Inter } from "next/font/google";
const inter = Inter({ subsets: ["latin"] });
import { i18n, type Locale } from "../../i18n-config";

export const metadata: Metadata = {
  title: "simple' portfolio",
  description: "Generated by create next app",
};

export async function generateStaticParams() {
  // 使用i18n配置中的locales属性，映射生成包含语言代码的对象数组
  return i18n.locales.map((locale) => ({ lang: locale }));
};

export default function RootLayout({
  children,
  params
}: Readonly<{
  children: React.ReactNode;
  params: { lang: Locale };
}>) {
  return (
    <html lang={params.lang}>
      <body
        className={cn(`${inter.className}`, 'flex flex-col h-screen bg-[--basic-bg] overflow-y-hidden dark')}
      >
        <HeaderNav />
        <main className="flex-[1]">
          <WagmiConfigProvider>
            {children}
          </WagmiConfigProvider>
        </main>
        <Toaster />
      </body>
    </html>
  );
}
