import type { Metadata } from "next";
import localFont from "next/font/local";
import "../styles/globals.css";
import { cn } from "@/lib/utils";
import HeaderNav from "@/components/HeaderNav/HeaderNav";
import WagmiConfigProvider from "@/contexts/WagmiProvider";
import { Inter } from "next/font/google";

const inter = Inter({ subsets: ["latin"] });

export const metadata: Metadata = {
  title: "simple' portfolio",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body
        className={cn(`${inter.className}`, 'flex flex-col h-screen bg-[--basic-bg] overflow-y-hidden dark')}
      >
        <HeaderNav />
        <main className="flex-[1]">
          <WagmiConfigProvider>
            {children}
          </WagmiConfigProvider>
        </main>
      </body>
    </html>
  );
}
