import type { Metadata } from "next";
import localFont from "next/font/local";
import "../styles/globals.css";
import { cn } from "@/lib/utils";
import HeaderNav from "@/components/HeaderNav/HeaderNav";
import WagmiConfigProvider from "@/contexts/WagmiProvider";

const geistSans = localFont({
  src: "./fonts/GeistVF.woff",
  variable: "--font-geist-sans",
  weight: "100 900",
});
const geistMono = localFont({
  src: "./fonts/GeistMonoVF.woff",
  variable: "--font-geist-mono",
  weight: "100 900",
});

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body
        className={cn(`${geistSans.variable} ${geistMono.variable} antialiased`, 'flex flex-col h-screen')}
      >
        <HeaderNav />
        <main className="flex-[1]">
          <WagmiConfigProvider>
            {children}
          </WagmiConfigProvider>
        </main>
      </body>
    </html>
  );
}
